### PR TITLE
Added VPI backend with GHDL and IVerilog support

### PR DESCRIPTION
**Pull request by bellaz89**
In this pull request I added a generic VPI backend.
At the moment I am able to perform simulations with GHDL and IVerilog.
See  #146 for more details

### CODE REVIEW

**Comment by Dolu1990** [comment]
Nice thanks :D

I have to test that :D
About verification / stress tests, we can reuse all the SpinalSim ones which are actualy running on Verilator. Shouldn't be complicated, i will check that too.

**Comment by bellaz89** [comment]
@Dolu1990 

Good :)

**Comment by Dolu1990** [comment]
Work on my side too ^^
So i will integrate that futher in the SpinalHDL flow, all good for you ?
Thanks again :D

**Comment by bellaz89** [comment]
Yep!

Thank you for helping me integrate this feature :)

**Pull request merged**
