### PR TITLE
Add AFix rounding range tests

### PR DESCRIPTION
**Pull request by kleinai**
This models the expected new bounds after rounding and compares that to what ranges AFix generates when rounding.

This test is currently broken pending review of the rounding ranges calculations.

### CODE REVIEW

**Comment by kleinai** [comment]
Unsurprisingly using BigDecimals to calculate the range will work. I do think it's best we keep the backing range as BigInts to avoid having to stuff non-trivially representable numbers (stuff like 0.1) into fixed points.

**Comment by Dolu1990** [comment]
Yes, BigDecimal scare me XD Would realy be better to stay as much as possible with BigInt to keep things "pure" ^^

**Comment by kleinai** [comment]
I'll rewrite the rounds to work on BigInt instead.  These new tests have already caught one rounding bug.

**Comment by kleinai** [comment]
After much pain, I have converted the clean BigDecimal code into a monster of BigInt code

**Comment by kleinai** [comment]
I think it's good to go. I'll bring it in.

**Pull request merged**
