### PR TITLE
Bitwise operators for Vec

### PR DESCRIPTION
**Pull request by numero-744**
Builds but untested.

### CODE REVIEW

**Comment by Dolu1990** [comment]
Good do me ^^

**Comment by Dolu1990** [comment]
ready for merge ?

**Comment by numero-744** [comment]
Well, I have not tested it yet (I have started reading about unit testing with sbt but did not play with it yet).

But if you are sure it is okay, you can merge it :)

**Comment by Dolu1990** [comment]
Hmm we may want to add an assert to ensure the size of both vec is the same ?
Zipped is a bit too relaxed ^^

**Comment by Dolu1990** [comment]
Thanks ^^

**Pull request merged**
