### PR TITLE
Wishbone bus and utilities

### PR DESCRIPTION
**Pull request by wifasoi**
This PR will add a preliminary wishbone bus interface, some "lego blocks"
(like: Arbiter,Decoder,Intercon,Adapter,SlaveFactory,WishboneUartCtrl)
and simulation utilities for generating and receiving simple wishbone transaction.
More work need to be done, but I think the code/class/componets are in a usable state.
I made some simple test in silicon (tested only the WishboneArbiter and WishboneUartCtrl) with sucess
This is my first time with scala (and SpinalHDL), so feedback is welcome (and appreciated)

### CODE REVIEW

**Comment by Dolu1990** [comment]
Hooo that's much !
Thanks, i have to review all of this ^^

**Comment by Dolu1990** [comment]
Sorry for the delay, i was in workshop all the week XD
Should be able to review the code tomorrow :)

**Comment by Dolu1990** [comment]
There is the review : 
Wishbone => 
- There is some unconstraint Bits() definition, Bits() stuff is working in some cases, but is dangerous and will not allow  withOf(xxx), so if possible it should be avoided
- About the <>/<->/connectTo functions, they will only work if one of the two interface is set as master/slave of a component, if you have two interface defined as internals of a component it won't be able to infer the connection direction, that's way it is probably preferable to have as low level interconnection primitives an << operator which explicitly specify the interface from the master(right opperand) and the interface from the slave (left opperand). See the Axi4 >> / <<. Then on the top of that we can implement the <> and compagnies ^^. You can ask if an interface is master slave with "myInterface.isMasterInterface"
WishboneAdapter =>
- StateMachine API has a hidden boot state, so the state machine isn't ready the very first cycle.
- io.wbm.STALL.removeAssignments() <3
WishboneArbiter => 
- OHMasking.roundRobin(status.asBits, B(priority)) => 
  - the priority argument of the roundRobin function isn't realy working that way. Basicaly it is a one hot value which say which input has the priority. You can find an example in the AhbLite3Arbiter. Ask me more info if required ^^
WishboneDecoder => 
- Using clearAll and then conditionaly assign the right interface together isn't optimal, it will infer some extra logic to clear signals like the slave addresses, even if each slave addresses could be constantly driven from the master address. The best is probably to constantly drive all slave inputs as much as you can with some and gateing on the arbitration signals, and for the slave to master connections to have MuxOH (see spinal.lib :))
WishboneGPIO => 
- About the naming, it's realy about taste and color, but most the Spinal lib would name it as WishboneGpio ^^ (see Apb3Gpio)
SpinalSimWishboneGpioTester => 
- Test should be placed into the test folder, not the main one. This way it will not be packaged into the SpinalHDL releases. Also i'm not sure that when i run regressions it will be picked if it's placed in main.
- Is the test passing for you ? The test faild on my laptop. Failure at 0, with DAT_MISO: 77 DAT_MOSI: 207
WishboneSlaveFactory =>
- :D

About the code style, everything is fine ^^
How do you wanna process for the merge ?  I  can already merge it into Dev with the main fixes about the Wishbone definitions itself, then you can merge back into your repository and continue ?
Thanks !

**Comment by Dolu1990** [comment]
How it is going ^^ ?

**Comment by wifasoi** [comment]
Hi, sorry for my slow progress.. this is a busy mouth for me.
A summary:
the wishbone implementation is completed... only need to cherry pick some commit on the UVMwishbone branch to fix some bug i found.
this pull request is missing a unit test for testing the wishbone intercon with the old wishbone testing utilities.
Now i'm refactoring the wishbone sim utilities (in the UVMwishbone branch), and creating new unit test. this is why i did not ask you to push this branch yet

**Comment by Dolu1990** [comment]
Miaouuuu

**Comment by Dolu1990** [comment]
How things are going ^^ ?

**Comment by wifasoi** [comment]
You got me,
I'm still working on it (need some cleanup here and there) but the Wishbone intercon seams to function well on the simulator: https://imgur.com/a/r6o7aPn
Need to cleanup the code from some spurious comment and update/add all the docstring. I'm think i can knock that out by the end of the week.
Unfortunally the UVM idea was a dead end... and i lost my progress because my laptop died... so here we are. If you want you can start the review (at your leisure) (the code now is more or less final). Sorry for the enormous delay by my part.. <insert cliché excuse about life and stuff here>

**Comment by Dolu1990** [comment]
No worries ^^
I will check it then :)

**Comment by wifasoi** [comment]
Do your worst, if you don't like something don't hold your comment back :)

**Comment by wifasoi** [comment]
I'm not yet finished with the Wishbone implementation..
I noticed there was no unitest for the WishboneSlaveFactory.. i implemented a simple unitest and found some bug. In the following days I'll rework the slave factory implementation.
so, I'll rework the Wishbone.scala definition (only refractory some function name) and the WishboneSlaveFactory.scala

**Comment by wifasoi** [comment]
TODO: need to scale down some unit-test, so travis doesn't complain (travis complains because the spinalWishboneIntercon require too much time to compile in verilator (for a good reason... the intercon size is massive (like 40 master and 10 slaves)
TODO: delete all the .withWave on my unit-test
Do not merge before this changes are made :)

**Comment by wifasoi** [comment]
Some status on the PR: almost done, the only important TODOs are:
- [ ] create basic testing for things added in 6302030f39c694e9985e561cc68f48ed59126211 (Added some functions for driving as slave the wishbone bus)

- [ ] change the intercon unitest, now the checking part is disabled (for troubleshooting reasons)

**Comment by abyszuk** [comment]
Hi, I'm just a regular person but I've wanted to ask about status of this PR.
I'm just starting with SpinalHDL and I like it very much.
But to be really useful in my projects I need Wishbone support, so I'm keeping my fingers crossed for your work.
Thanks!

**Comment by wifasoi** [comment]
The PR is ready to merge (after some code review) (IMHO)

**Comment by Dolu1990** [comment]
Great. so,i made some review, it look good :D
So let's merge it ?

Just for the WishboneInterconFactory, I recently added https://github.com/SpinalHDL/SpinalHDL/blob/dev/lib/src/main/scala/spinal/lib/bus/simple/PipelinedMemoryBus.scala#L222

It do address width adapation by default, and allow setting connectors in a second time, there is an example : 
https://github.com/SpinalHDL/VexRiscvSoftcoreContest2018/blob/master/hardware/scala/riscvSoftcoreContest/Igloo2Perf.scala#L238

About X.setPartialName(Y, prefix), basicaly, (and it could have named better) it set X as a child owned by Y, and add the prefix on the name (Used for Bundles). But the best way actualy is to use setCompositeName, which only play with names in a quite similar way, but without the child/owner stuff.
There is an example
https://github.com/SpinalHDL/SpinalHDL/blob/dev/lib/src/main/scala/spinal/lib/bus/simple/PipelinedMemoryBus.scala#L284
Also the good thing with setCompositeName, is that if X and Y aren't in the same component, it will prefix the name with the Y component + Y name. For example : 
system_apbBridge_io_pipelinedMemoryBus_arbiter

**Comment by wifasoi** [comment]
give me a day or two and I'll fix/add what you asked.

**Comment by Dolu1990** [comment]
Ok :)

**Comment by Dolu1990** [comment]
Just as info, on the PipelinedMemoryBus, the >> operator allow to reduce the width of address automaticaly (for convenancy)
And this is use in the interconnect stuff :
https://github.com/SpinalHDL/SpinalHDL/blob/dev/lib/src/main/scala/spinal/lib/bus/simple/PipelinedMemoryBus.scala#L309

**Comment by Dolu1990** [comment]
Hoo
One thing is, when everything is ok, i will change the pull request target branch from master to dev, dev will be merged into master before each SpinalHDL release :)

**Comment by Dolu1990** [comment]
Just let's me know when you are ready

**Comment by wifasoi** [comment]
I think think the last two commit will fix all the issue you addressed.
I changed the destination of the PR to dev also

**Comment by Dolu1990** [comment]
Great :D

**Comment by Dolu1990** [comment]
No worries for the regressions, that's a Java7 support issue on travis ^^

**Pull request merged**
