### PR TITLE
Move cocotb outputs to seperate folder

### PR DESCRIPTION
**Pull request by andreasWallner**
This is currently a try for #1029, since I can't easily get cocotb to work on my machine.

# Context, Motivation & Description

Less clutter in the root directory

# Impact on code generation

None

# Checklist

- ~[ ] Unit tests were added~
- ~[ ] API changes are or will be documented:~

### CODE REVIEW

**Comment by Readon** [comment]
good experiments. it seems that the failed tester are about rom cocotb.

**Comment by Readon** [comment]
I have also tried to continue this work several days ago. The main problem seems caused by SpinalVerilog and SpinalVHDL related files. details can refer to Readon/SpinalHDL dev branch. Wish it helps.

**Comment by andreasWallner** [comment]
Sorry for the spam, for some reason cocotb (from the OSS-CAD-Suite) does not work correctly so I resorted to pushing a few times... 
The few failing testcases in the beginning had hardcoded paths, but when moving the simulation traces as well I broke it again...

**Comment by Readon** [comment]
> Sorry for the spam, for some reason cocotb (from the OSS-CAD-Suite) does not work correctly so I resorted to pushing a few times... The few failing testcases in the beginning had hardcoded paths, but when moving the simulation traces as well I broke it again... - thanks for the hint, I'll have a look.

You'are welcome to test and merge the code that I have tried to fix. 
I am too busy to fix the last problem, which can help to keep the changes in tester minimal.

**Comment by Readon** [comment]
@andreasWallner do you think this is ready? I have created a PR to you repository, which is based on this PR.
I think we need to get this merge first.

**Comment by andreasWallner** [comment]
Close in favor of #1053

**Pull request closed without merging**
