### PR TITLE
Scala 2.13 build fixes

### PR DESCRIPTION
**Pull request by dlmiles**
[info] Tests: succeeded 939, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.

This appears to be all that was needed.

### CODE REVIEW

**Comment by dlmiles** [comment]
```
[error] /tmp/spinalhdl_SpinalHDL/tester/src/test/scala/spinal/tester/code/Debug.scala:633:45: can't supply unit value with infix notation because nullary method simPublic: (): spinal.core.UInt takes no arguments; use dotted invocation instead: spinal.core.sim.`package`.SimDataPimper[spinal.core.UInt](spinal.core.Reg.apply[spinal.core.UInt](core.this.HardType.implFactory[spinal.core.UInt](spinal.core.`package`.UInt(spinal.core.`package`.IntToBuilder(8).bits)), spinal.core.Reg.apply$default$2[Nothing], spinal.core.Reg.apply$default$3[Nothing]).init(spinal.core.`package`.IntToUInt(0))).simPublic()
[error]     val counter = Reg(UInt(8 bits)) init(0) simPublic()
[error]                                             ^
[error] /tmp/spinalhdl_SpinalHDL/tester/src/test/scala/spinal/tester/scalatest/AnalogConnectionTester.scala:95:33: can't supply unit value with infix notation because nullary method setAsComb: (): spinal.core.Bool takes no arguments; use dotted invocation instead: $anon.this.pad.apply(i).setAsComb()
[error]           tri(i).read := pad(i) setAsComb()
[error]                                 ^
[error] /tmp/spinalhdl_SpinalHDL/tester/src/test/scala/spinal/tester/scalatest/BitVectorTests.scala:45:10: ambiguous reference to overloaded definition,
[error] both method apply in object Cat of type [T <: spinal.core.Data](data: Iterable[T]): spinal.core.Bits
[error] and  method apply in object Cat of type (data: spinal.core.Data*): spinal.core.Bits
[error] match argument types (spinal.core.Vec[SliceDutBits.this.i.T]) and expected result type ?
[error]     o := Cat(split)
[error]          ^
[error] /tmp/spinalhdl_SpinalHDL/tester/src/test/scala/spinal/tester/scalatest/BitVectorTests.scala:55:10: ambiguous reference to overloaded definition,
[error] both method apply in object Cat of type [T <: spinal.core.Data](data: Iterable[T]): spinal.core.Bits
[error] and  method apply in object Cat of type (data: spinal.core.Data*): spinal.core.Bits
[error] match argument types (spinal.core.Vec[SliceDutSlices.this.i.T]) and expected result type ?
[error]     o := Cat(split)
[error]          ^
[error] four errors found
[error] (tester / Test / compileIncremental) Compilation failed
[error] Total time: 86 s (01:26), completed May 10, 2023, 4:02:07 AM
```

**Comment by Dolu1990** [comment]
Scala 2.13 / Scala 3 are such a paine XD

**Comment by Dolu1990** [comment]
thanks ^^

**Comment by Readon** [comment]
this PR fails CI currently. @dlmiles

**Pull request merged**
