### PR TITLE
fix: fix OS version to ubuntu20 and revert to build iverilog into cache.

### PR DESCRIPTION
**Pull request by Readon**
Closes #

# Context, Motivation & Description

To make sure the current CI working and fill the time gap to @numero-744 's new CI.
Temporarily fix OS version to ubuntu20 and revert to build iverilog into cache.

# Impact on code generation

# Checklist

- [ ] ~~Unit tests were added~~
- [ ] ~~API changes are or will be documented:~~
  - using Scaladoc comments: `/** */`?
  - on [RTD](https://github.com/SpinalHDL/SpinalDoc-RTD)?
  - thanks to a [new tracking issue on RTD](https://github.com/SpinalHDL/SpinalDoc-RTD/issues/new?title=Document%20XXX&body=Do%20not%20merge%20until%20SpinalHDL/SpinalHDL%23XXX%20has%20not%20been%20merged)?

### CODE REVIEW

**Comment by Readon** [comment]
@numero-744 If the new CI is not going to be work very soon, I suggest to fall back to previous one first.

**Comment by numero-744** [comment]
I just have to fix an issue with cocotb, I'll fix it when I have time

**Comment by Readon** [comment]
> I just have to fix an issue with cocotb, I'll fix it when I have time

I think the current CI cache can work, it's not necessary to merge this temporarily.

**Comment by Readon** [comment]
> have to fix an issue with cocotb, I'll fix it when I have time



> I just have to fix an issue with cocotb, I'll fix it when I have time

Ok, I will merge this first due to #994 is still fail while testing.

**Comment by numero-744** [comment]
It seems this PR, by reverting a workaround, unsurprisingly re-introduced the issue the workaround was fixing, aka:

```
 parse.cc:140:10: fatal error: parse.hh: No such file or directory
...
 /home/runner/.local/lib/python3.10/site-packages/cocotb/share/makefiles/simulators/Makefile.icarus:53: *** Unable to locate command >iverilog<.  Stop.
```

Except when caching makes it look like it works

**Pull request merged**
