### PR TITLE
ci: scaladoc to gh-pages

### PR DESCRIPTION
**Pull request by numero-744**
See commit descriptions.

Preview available here for `dev` branch: https://numero-744.github.io/SpinalHDL/dev/

### CODE REVIEW

**Comment by numero-744** [comment]
@Dolu1990 for review and merge if approved

**Comment by Dolu1990** [comment]
single-commit option to be added ^^

**Comment by numero-744** [comment]
I will add it, then :wink:

I added sim to the built things, but I think I mixed things up. `import spinal.sim._` is deprecated in favor of `import spinal.core.sim._`, right? Then I should not add `sim` to the generated docs I guess?

**Comment by numero-744** [comment]
Preview is up again :smile:

**Comment by numero-744** [comment]
So I have removed `spinal.sim` from the docs as I mentioned earlier.

**Comment by Dolu1990** [comment]
> import spinal.sim._

Yes right, that one should never be used. Always import spinal.core.sim._   :)

**Comment by numero-744** [comment]
So it's ready for final review and merge @Dolu1990

**Comment by Dolu1990** [comment]
Still the issue of : 

scalaVersion := SpinalVersion.compilers(1),

Would much safer to stay with scalaVersion := SpinalVersion.compilers(0)

(sbt madness when using submodules)

**Comment by numero-744** [comment]
In the long term using a too old minor version will be an issue for tools support. Also version 0 makes the docs really ugly.

Do you have any references about this issue with submodules?

**Comment by Dolu1990** [comment]
Ahhhh yes, SpinalVersion.compilers(1) break stuff, ex SaxonSoc: 

```scala
sbt:SaxonSoc> compile
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/media/data/open/SaxonSoc/efinix/SaxonEFX_Soc/ext/VexRiscv/"), "root"):
[error]    com.github.spinalhdl:spinalhdl-core _2.11, _2.12
[error]    com.github.spinalhdl:spinalhdl-lib _2.11, _2.12
[error]    com.github.spinalhdl:spinalhdl-sim _2.11, _2.12
[error]    com.github.spinalhdl:spinalhdl-idsl-payload _2.11, _2.12
[error]    com.github.spinalhdl:spinalhdl-idsl-plugin _2.11, _2.12
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/media/data/open/SaxonSoc/efinix/SaxonEFX_Soc/ext/NaxRiscv/"), "root"):
[error]    com.github.spinalhdl:spinalhdl-core _2.11, _2.12
[error]    com.github.spinalhdl:spinalhdl-lib _2.11, _2.12
[error]    com.github.spinalhdl:spinalhdl-sim _2.11, _2.12
[error]    com.github.spinalhdl:spinalhdl-idsl-payload _2.11, _2.12
[error]    com.github.spinalhdl:spinalhdl-idsl-plugin _2.11, _2.12
[error] stack trace is suppressed; run last ProjectRef(uri("file:/media/data/open/SaxonSoc/efinix/SaxonEFX_Soc/ext/VexRiscv/"), "root") / update for the full output
[error] stack trace is suppressed; run last ProjectRef(uri("file:/media/data/open/SaxonSoc/efinix/SaxonEFX_Soc/ext/NaxRiscv/"), "root") / update for the full output
[error] (ProjectRef(uri("file:/media/data/open/SaxonSoc/efinix/SaxonEFX_Soc/ext/VexRiscv/"), "root") / update) Conflicting cross-version suffixes in: com.github.spinalhdl:spinalhdl-core, com.github.spinalhdl:spinalhdl-lib, com.github.spinalhdl:spinalhdl-sim, com.github.spinalhdl:spinalhdl-idsl-payload, com.github.spinalhdl:spinalhdl-idsl-plugin
[error] (ProjectRef(uri("file:/media/data/open/SaxonSoc/efinix/SaxonEFX_Soc/ext/NaxRiscv/"), "root") / update) Conflicting cross-version suffixes in: com.github.spinalhdl:spinalhdl-core, com.github.spinalhdl:spinalhdl-lib, com.github.spinalhdl:spinalhdl-sim, com.github.spinalhdl:spinalhdl-idsl-payload, com.github.spinalhdl:spinalhdl-idsl-plugin
[error] Total time: 2 s, completed Oct 28, 2022, 9:58:33 AM
sbt:SaxonSoc> 
```

Will try to find a solution

**Pull request merged**
