### PR TITLE
Interrupt Register Interface on regif  redesign

### PR DESCRIPTION
**Pull request by jijingg**
Referring to  common practices, the interrupt register interface is redesigned

It is mainly divided into two categories

**1.  Pulse event trigger, record and merge**  
- RAW  
- FORCE
- MASK  
- STATUS
```scala 
io.sys_int  := busif.interruptFactory("SYS",io.int_pulse0, io.int_pulse1, io.int_pulse2, io.int_pulse2)
```
 

**2. Interrupt level merge**    
- MASK  
- STATUS
```
io.gpio_int := busif.interruptLevelFactory("GPIO",io.int_level0, io.int_level1,io.int_level1,io.int_level1,)
```
MS2

**Example** ：
```scala 
class RegFileIntrExample extends Component{
  val io = new Bundle{
    val apb = slave(Apb3(Apb3Config(16,32)))
    val int_pulse0, int_pulse1, int_pulse2, int_pulse3 = in Bool()
    val int_level0, int_level1, int_level2 = in Bool()
    val sys_int = out Bool()
    val gpio_int = out Bool()
  }

  val busif = BusInterface(io.apb,  (0x000,1 KiB), 0, regPre = "AP")
  io.sys_int  := busif.interruptFactory("SYS",io.int_pulse0, io.int_pulse1, io.int_pulse2, io.int_pulse3)
  io.gpio_int := busif.interruptLevelFactory("GPIO",io.int_level0, io.int_level1, io.int_level2, io.sys_int)

  def genDoc() = {
    busif.accept(CHeaderGenerator("intrreg.h","Intr"))
    busif.accept(HtmlGenerator("intrreg.html", "Interupt Example"))
    busif.accept(JsonGenerator("intrreg.json"))
    this
  }

  this.genDoc()
}
```
截屏2022-04-13 上午1 34 57

### CODE REVIEW

**Comment by Readon** [comment]
Good work. 
I wonder that is priority important in common usage? 
I did not use priority a lot,  but it always been introduced in computer design related courses.

**Comment by Dolu1990** [comment]
Let me know when you think i can merge :)

**Comment by jijingg** [comment]
> I wonder that is priority important in common usage?
> I did not use priority a lot, but it always been introduced in computer design related courses.

@Readon  right, that's another topic of GIC(General Interrupt Control) usually in the CPU.  If necessary,  mybe we can add a lib of GIC later. 
here is a basic Interrupt register interface solution always used in IP/modules/sub_system.

@Dolu1990 , it's ready for merge

**Comment by Dolu1990** [comment]
Thanks ^^

**Pull request merged**
