### PR TITLE
DFI Interface

### PR DESCRIPTION
**Pull request by LurenAA**
Closes #

# Context, Motivation & Description

I would like to add support for the DFI protocol(DDR PHY Interface), which may be useful for the development of certain SDRAM controllers.

# Impact on code generation

# Checklist

- [ ] Unit tests were added
- [ ] API changes are or will be documented:
  - using Scaladoc comments: `/** */`?
  - on [RTD](https://github.com/SpinalHDL/SpinalDoc-RTD)?
  - thanks to a [new tracking issue on RTD](https://github.com/SpinalHDL/SpinalDoc-RTD/issues/new?title=Document%20XXX&body=Do%20not%20merge%20until%20SpinalHDL/SpinalHDL%23XXX%20has%20not%20been%20merged)?

### CODE REVIEW

**Comment by Readon** [comment]
So the next step would be 
1. A DDR SDRAM controller use DFI as master port.
2. Write at least one wrapper for DFI to Vivado Serdes connection.

**Comment by Dolu1990** [comment]
> So the next step would be
> 
> 1. A DDR SDRAM controller use DFI as master port.
> 2. Write at least one wrapper for DFI to Vivado Serdes connection.

There is already a DDR2 / DDR3 / SDR controller in the lib : 
https://github.com/SpinalHDL/SpinalHDL/tree/dev/lib/src/main/scala/spinal/lib/memory/sdram/xdr

As phy is has Artix 7 support (serdes)

But the phy interface is different.

**Comment by Readon** [comment]
> > So the next step would be
> > 
> > 1. A DDR SDRAM controller use DFI as master port.
> > 2. Write at least one wrapper for DFI to Vivado Serdes connection.
> 
> There is already a DDR2 / DDR3 / SDR controller in the lib : https://github.com/SpinalHDL/SpinalHDL/tree/dev/lib/src/main/scala/spinal/lib/memory/sdram/xdr
> 
> As phy is has Artix 7 support (serdes)
> 
> But the phy interface is different.

Yes, this work is to fit the legacy controller with more support on DFI, so that the phy can be decoupled from the controller.

**Comment by Dolu1990** [comment]
Hi, sorry for the delay.

I think we can go like this. Thanks :)

**Pull request merged**
