### PR TITLE
WIP: Attempt to make Tilelink framework generic

### PR DESCRIPTION
**Pull request by kleinai**
Creating this more as an RFC. Playing around with how the Tilelink framework might be adapted to host itself and other buses with less work. More or less a copy and paste of Tilelink with parameters.

Closes #

# Context, Motivation & Description

# Impact on code generation

# Checklist

- [ ] Unit tests were added
- [ ] API changes are or will be documented:
  - using Scaladoc comments: `/** */`?
  - on [RTD](https://github.com/SpinalHDL/SpinalDoc-RTD)?
  - thanks to a [new tracking issue on RTD](https://github.com/SpinalHDL/SpinalDoc-RTD/issues/new?title=Document%20XXX&body=Do%20not%20merge%20until%20SpinalHDL/SpinalHDL%23XXX%20has%20not%20been%20merged)?

### CODE REVIEW

**Comment by Dolu1990** [comment]
Hi ^^
So, i was kind of thinking about it too. About having some more generic sceleton code using type parameter.

I can see that there is code which could be shared between different bus implementation of the Node class, i'm just mostly not sure of the best way to reuse that code.

In some ways, it seems to me that the following look scary:

```scala
class NodeBase[T <: Bundle, C, DC <: DeferredConfig[C], N <: NodeBase[T, C, DC, N, CB], CB <: ConnectionBase[T, C, DC, N, CB]] 
```

I will take some time to think about it, to see if there would not be another way :)

**Comment by Dolu1990** [comment]
Ahhh interresting, i didn't knew about this syntax XD

**Comment by kleinai** [comment]
Way better to use a trait then build an object.  The classes can be define in an object and share types without needed all the parameter headache.

Usage:
```scala
object Axi4TileLink extends TileLinkApi {
  type T = Axi4
  type C = Axi4Config
  type DC = Config
  type N = Axi4Node
  type CB = Axi4Connection
 
  ... define classes ...
}
```

Example snippet:
```scala
object Example0 extends App {
  SpinalVerilog(new Module {
    import Axi4TileLink._

    val cpuBus = new Axi4Node().setSlaveOnly()
    val debugBus = new Axi4Node().setSlaveOnly()
    val mainBus = new Axi4Node()
    val ramBus = new Axi4Node().setMasterOnly()
    val peripheralBus = new Axi4Node().setMasterOnly()

   ... code ...
```

**Comment by Dolu1990** [comment]
> object Axi4TileLink extends TileLinkApi {

That's a interresting pattern ^^

Hmmmm
I'm still looking around to see if things could be instead more "composed" (to try avoid too much generalization). I pushed the following ( WIP ) : 
https://github.com/SpinalHDL/SpinalHDL/commit/4a33fe066d6a17874c67f3353baf2e573031755f#diff-9c56d14d6a1ec1cfff255c2b4f33e0562ee3f984b60ce88d3767099ee02eeb77

**Comment by Dolu1990** [comment]
I think https://github.com/SpinalHDL/SpinalHDL/pull/1160 would be more or less ok.

**Comment by Dolu1990** [comment]
https://github.com/SpinalHDL/SpinalHDL/pull/1160 merged :)

**Pull request closed without merging**
