### PR TITLE
Mill project file updated.

### PR DESCRIPTION
**Pull request by Readon**
Closes #

# Context, Motivation & Description

Update dependent packages' version and use tester the same as `sim`, `core`, `lib`, `tester`.

# Impact on code generation

# Checklist

- [ ] Unit tests were added
- [ ] API changes are or will be documented:
  - using Scaladoc comments: `/** */`?
  - on [RTD](https://github.com/SpinalHDL/SpinalDoc-RTD)?
  - thanks to a [new tracking issue on RTD](https://github.com/SpinalHDL/SpinalDoc-RTD/issues/new?title=Document%20XXX&body=Do%20not%20merge%20until%20SpinalHDL/SpinalHDL%23XXX%20has%20not%20been%20merged)?

### CODE REVIEW

**Comment by Readon** [comment]
The default is set to 2.12.
use `mill tester[].compile` could call `tester[2.12.18].compile`

**Comment by Readon** [comment]
@KireinaHoro Does this affect your project significantly?

**Comment by KireinaHoro** [comment]
Pulled locally and tested.  Other than you changed the name of the trait `CrossTester` to `Tester`, requiring downstream module definitions to change accordingly as well, no other changes needed.

**Comment by Dolu1990** [comment]
Why updating the dependencies ?
In particular, i remember that ivy"net.openhft:affinity:3.21ea1.1", was a real pain to find a version which wasn't broken on one of the platform ^^ (it that isn't broken, better not updating it)

**Comment by Readon** [comment]
The main target is to add test for all scala versions in tests.
Still need to wait com-lihaoyi/mill#3440 solved.

**Comment by Dolu1990** [comment]
> Why updating the dependencies ? In particular, i remember that ivy"net.openhft:affinity:3.21ea1.1", was a real pain to find a version which wasn't broken on one of the platform ^^ (it that isn't broken, better not updating it)
it's copied from sbt version.

It would say, don't update that one, it realy broke stuff by the past on some not so known platforms

**Comment by Readon** [comment]
> > Why updating the dependencies ? In particular, i remember that ivy"net.openhft:affinity:3.21ea1.1", was a real pain to find a version which wasn't broken on one of the platform ^^ (it that isn't broken, better not updating it)
> > it's copied from sbt version.
> 
> It would say, don't update that one, it realy broke stuff by the past on some not so known platforms



> > Why updating the dependencies ? In particular, i remember that ivy"net.openhft:affinity:3.21ea1.1", was a real pain to find a version which wasn't broken on one of the platform ^^ (it that isn't broken, better not updating it)
> > it's copied from sbt version.
> 
> It would say, don't update that one, it realy broke stuff by the past on some not so known platforms

I have checked [here](https://github.com/SpinalHDL/SpinalHDL/blob/e52c326682d87d7109437688935d6443c8399c2e/build.sbt#L122), it was updated one year ago.

**Comment by Dolu1990** [comment]
> I have checked [here](https://github.com/SpinalHDL/SpinalHDL/blob/e52c326682d87d7109437688935d6443c8399c2e/build.sbt#L122), it was updated one year ago.

Ahhhhhhhhhhhh
damned XD, sorry i was confused XDXD

All good, feel free to merge when you want ^^

**Pull request merged**
