### PR TITLE
add createSelector to Mux and Demux IO.

### PR DESCRIPTION
**Pull request by Readon**
with corresponding verification.

### CODE REVIEW

**Comment by Readon** [comment]
fix #869

**Comment by Readon** [comment]
I think the doc needed label should be assigned after the PR is merged, due to there are would be PR will not be merged.

**Comment by Readon** [comment]
> Hmm, maybe, instead of having doc needed tag in the SpinalHDL repo, another issue should be open in the SpinalDoc-RTD repo. I don't know what is the best aproache
> 
> The issue i see is that this will start to create many many issue / to track stuff, and endup making the whole flow cumbersome XD

Emm, that's really a problem, is there best practice that GitHub recommanded?

**Comment by numero-744** [comment]
Yes the idea is to have tracking issues.

This is why the description (if you let your mouse on the label) is that there is no documentation or tracking issue. So you can either open an issue so that we do not forget it misses documentation (and document it soon™); or open a PR with the documentation, and do not merge it before the code PR is merged.

**Comment by numero-744** [comment]
> The issue i see is that this will start to create many many issue / to track stuff, and endup making the whole flow cumbersome XD

IMO having tracking issues is useful to not forget things and see how much things are not documented, to act and keep things documented for users. Having features not documented for a public project is as useful as not implementing these features.

**Comment by numero-744** [comment]
> Cross repository PR is really not friendly.

I agree. We have to do two pull requests which have a dependency in time (do not merge docs before the code) because RTD is in a distinct repository. To be honest I think there is no better way to have an RTD, and having an RTD is user-friendly (discussed in https://github.com/SpinalHDL/SpinalDoc-RTD/issues/26).

**Comment by Dolu1990** [comment]
In some ways, the SpinalDoc-RTD documentation often has to come later, when the feature has been used a bit and stabilised after some time. 
To me, if the functions added aren't self explenatory enough by their own name / parameter name, adding some scala comments / scala doc is enough. I guess ?

So, i'm not sure coupling too strongly SpinalHDL and SpinalDoc is a good thing.

Also, i think for a PR if this kind, in code doc is good enough.

**Comment by numero-744** [comment]
> Ahhh, the topic is far away from the original one, I will merge if it is good enough.

True XD
If you want, feel free to re-open #899 to discuss docs management.

**Pull request merged**
