### PR TITLE
perf: make UIntToOh faster in simulation

### PR DESCRIPTION
**Pull request by tanhongze**

### CODE REVIEW

**Comment by numero-744** [comment]
Fixes #873

**Comment by tanhongze** [comment]
A detail: what if `width=0`?

**Comment by Readon** [comment]
> A detail: what if `width=0`?

Then there would be also possibilities that value is larger than width.XD

**Comment by numero-744** [comment]
Maybe `width=0` is a special case because `B(1, width bits)` would fail?

If value > width > 0 it would just return 0 I guess?

**Comment by numero-744** [comment]
I think `require(width > 0)` is okay to manage too little width

For this the following part, isn't the default case already okay?

```scala
    if(width > (1<<widthOf(value))){
      val ret = B(1, 1<<widthOf(value) bits) |<< value
      return ret.resize(width)
    }
```

I mean, wouldn't this work with same behavior?

```scala
  def apply(value: UInt, width : Int): Bits = {
    require(width > 0)
    B(1, width bits) |<< value
  }
```

**Comment by numero-744** [comment]
I was going to say that there is an undriven signal with `width<=0`, well there cannot be design errors if there is nothing at all ^^'

LGTM if you have tested it :wink:

**Comment by Dolu1990** [comment]
So, i tested on yosys + ice40, and results seems the same.

Thanks for the PR ^^

**Pull request merged**
