### PR TITLE
feat(lib): Axi4 to AxiLite4 conversions

### PR DESCRIPTION
**Pull request by kleinai**
# Context, Motivation & Description

Adds simple conversion methods to go from Axi4 to AxiLite4 and vice versa.
ID remover (reflection) and unbursting (conversion) applied as needed.

# Impact on code generation

# Checklist

- [ ] Unit tests were added
- [ ] API changes are or will be documented:
  - using Scaladoc comments: `/** */`?
  - on [RTD](https://github.com/SpinalHDL/SpinalDoc-RTD)?
  - thanks to a [new tracking issue on RTD](https://github.com/SpinalHDL/SpinalDoc-RTD/issues/new?title=Document%20XXX&body=Do%20not%20merge%20until%20SpinalHDL/SpinalHDL%23XXX%20has%20not%20been%20merged)?

### CODE REVIEW

**Comment by Readon** [comment]
Good work.

Btw, AxiLite4 is a special case of Axi4 with 
``` scala
      useId = false,
      useRegion = false,
      useBurst = false,
      useLock = false,
      useCache = false,
      useSize = false,
      useQos = false,
      useLen = false,
```
Do you think it's worth to unify them into one by different config?
If we do so, it is not necessary to convert them.
Maybe the most complex work is to fit all facilities that existing.

**Comment by kleinai** [comment]
> Good work.

Thanks!

> Do you think it's worth to unify them into one by different config? If we do so, it is not necessary to convert them. Maybe the most complex work is to fit all facilities that existing.

I believe this conversation has been had before and the general consensus is no.  I don't have a preference either way so long as there are easy conversion methods.

**Comment by kleinai** [comment]
Also, I have tests I wrote while building these methods if we want those too.  Although this includes some rework of the AxiLite4 sim driver.

**Comment by Readon** [comment]
> Also, I have tests I wrote while building these methods if we want those too. Although this includes some rework of the AxiLite4 sim driver.

That would be helpful to have a test. Does the unmodified AxiLite4 sim driver works?
If a rework on AxiLite4 Sim driver is required, how about make a PR on that first?

**Comment by numero-744** [comment]
About tests, don't forget #1001

**Comment by Readon** [comment]
> About tests, don't forget #1001

I think it's in draft status still. ^^

**Comment by numero-744** [comment]
Yep, because I wanted to fix the CI first; and feedback is needed for the structure of the test directory.

**Comment by Readon** [comment]
Thanks, ^^.

**Pull request merged**
