### PR TITLE
(a)syncronous -> (a)synchronous

### PR DESCRIPTION
**Pull request by tomverbeure**
See PR #168 but now on the dev branch.

### CODE REVIEW

**Comment by Dolu1990** [comment]
Maybe because of this XD

**Comment by Dolu1990** [comment]
Hoo one thing, dev is now using sbt 1.2.7, moved to scala 2.11.12 and changed many little things in the flow. So if you want to try it out you will probably need to do a sbt clean compile

**Comment by Dolu1990** [comment]
In fact i restarted the travis build from the web interface XD

**Comment by Dolu1990** [comment]
hmm it look like you finaly realy need to merge SpinalHDL dev into your repo :)

**Comment by tomverbeure** [comment]
Suggested improvements were added.

**Pull request merged**
