### PR TITLE
Add GlobalClock and an example for async verfication.

### PR DESCRIPTION
**Pull request by Readon**

### CODE REVIEW

**Comment by Dolu1990** [comment]
Hi ^^

So if i understand well, GlobalClock is a tool to have one global clock generating syncronous sub clocks right ?

**Comment by Readon** [comment]
> Hi ^^
> 
> So if i understand well, GlobalClock is a tool to have one global clock generating syncronous sub clocks right ?

Yes, all the other clocks and resets are retrieved from the global clock. It's the minimum granularity time unit.

**Comment by Dolu1990** [comment]
Ahhh cool ^^
What is the domain.clock.addAttribute("gclk") for ?

**Comment by Readon** [comment]
> Ahhh cool ^^ What is the domain.clock.addAttribute("gclk") for ?

That is a yosys related syntax, to tell yosys that the clock is the global one.

It's a must for async design verification. I have tried to have an input clock instead, but yosys does not know it's global property.

**Comment by Readon** [comment]
Is there any concerns about this PR? @Dolu1990

**Comment by Dolu1990** [comment]
No all good ^^
I just losed track of the PR.

**Pull request merged**
