### PR TITLE
Deprecate Bool without braces

### LINKED ISSUE #972: Deprecate Bool function with no braces
I'm still not sure I understand why, but @Dolu1990 said it was not a good thing.

- [x] Deprecate `Bool`, should use `Bool()` instead
- [x] Check no deprecated syntax is in this repository
- [x] Check no deprecated syntax in RTD

### PR DESCRIPTION
**Pull request by numero-744**
Closes #972 

# Checklist

- [x] Deprecate `Bool`, should use `Bool()` instead
- [x] Check no deprecated syntax is in this repository
- [x] Check no deprecated syntax in RTD: https://github.com/SpinalHDL/SpinalDoc-RTD/pull/156

### CODE REVIEW

**Comment by numero-744** [comment]
PR ready for review, but don't merge it before I checked RTD for bad usage of `Bool`.

**Comment by numero-744** [comment]
Ready for review; please also review the RTD PR pointed to in the description and merge it first

**Comment by kleinai** [comment]
This is for better Scala 3 support?

**Comment by numero-744** [comment]
@kleinai see https://github.com/SpinalHDL/SpinalHDL/issues/972#issuecomment-1323803662

**Comment by likewise** [comment]
I remember the documentation has a few examples with Bool without braces, I think the Blackbox area.

**Comment by numero-744** [comment]
@likewise Hmm I should be updating everything in https://github.com/SpinalHDL/SpinalDoc-RTD/pull/156 but I might have missed something :thinking: Tell me if there is something wrong

**Comment by numero-744** [comment]
@kleinai another reason could be the language consistency: all hardware types (including both Spinal standard types, and user hardware types which should be mainly used via `case class`) take braces.

The RTD PR has been merged, any suggestions before I merge this one?

**Comment by kleinai** [comment]
No complaints. Complying with Scala 3 is going to be a challenge.

**Comment by Dolu1990** [comment]
> No complaints. Complying with Scala 3 is going to be a challenge.

Naaa, a real paine in the ass i would say XD

**Comment by Dolu1990** [comment]
Let's merge ?

**Pull request merged**
