### PR TITLE
[feature] Component add stub method for empty component use

### PR DESCRIPTION
**Pull request by jijingg**
@Dolu1990  as we talk in gitter . i add a stub method for component to get an empty Component

i have try to remove useless statement in component to instead `SpinalConfig(removePruned = true)` but faild . 

could you help me to add that

### CODE REVIEW

**Comment by Dolu1990** [comment]
Ahhh it was more tricky than what i was thinking.
So, clearning the children list of component isn't enough, it is also required to remove all connection to it.

Here is a version which reaaaaaly cleanup everything. It has to be done in two phase, (remove then patch) as when we iterate on stuff with the foreachStatements, it is difended to remove another node than the current one.

```scala
    def stub: this.type = this.rework{
      //First remove all we don't want
      this.children.clear()
      this.dslBody.foreachStatements{
        case bt : BaseType if !bt.isDirectionLess =>
        case s => s.removeStatement()
      }

      //Then patch things
      this.dslBody.foreachStatements{
        case bt : BaseType if bt.isOutput | bt.isInOut => {
          bt := bt.getZero
        }
        case s =>
      }
      this
    }
 ```
 
 let's me know if you have any question about it ^^

**Comment by jijingg** [comment]
> It has to be done in two phase, (remove then patch) as when we iterate on stuff with the foreachStatements, it is defended to remove another node than the current one or to add nodes.

here need iterate foreachStatement two times , I understand why caused me to fail all the time. 
now it work perfect

Basically, you have completed all the implementations of this PR , I just recorded it , haha ..   @Dolu1990

**Comment by Dolu1990** [comment]
No worries ^^
Just one thing, adding the brackets to def stub()
As this function has a side effect it is better for clarity.

**Comment by jijingg** [comment]
> Just one thing, adding the brackets to def stub()

done !

**Comment by Dolu1990** [comment]
thanks ^^

**Pull request merged**
