### PR TITLE
Component stub clock/reset removed bug fix

### PR DESCRIPTION
**Pull request by jijingg**
@Dolu1990 , Component stub method clock/reset accident removed bug fix

### CODE REVIEW

**Comment by Dolu1990** [comment]
hmmm using a phase thing there seems to me quite a bit dangerous.

What about instead doing something like ClockDomain.current.readClockWire, same for reset/clockEnable,softReset (if the signal existe)

**Comment by jijingg** [comment]
> hmmm using a phase thing there seems to me quite a bit dangerous.
> 
> What about instead doing something like ClockDomain.current.readClockWire, same for reset/clockEnable,softReset (if the signal existe)

I was thinking about it.  If there are multiple clocks, even submodules use `Clockdomain.external`, in those case, I don't know how to walk all clockdomain out.

**Comment by Dolu1990** [comment]
I isolated the behaviour of the phase in some API, you can use it that way PhasePullClockDomains.recursive(this)

**Comment by jijingg** [comment]
@Dolu1990  done!

**Pull request merged**
