### PR TITLE
add fp-interpolator to avoid errors in 2.13

### LINKED ISSUE #1559: Physical Number representation wrong on Scala 2.13
Scala 2.13's f-string parser would not call formatTo function in Formattable. 
This lead following lines failed.
``` scala
assert(f"${HertzNumber(5123000)}" == "5.123 MHz")
assert(f"${HertzNumber(5123000)}%s" == "5.123 MHz")
assert(f"${HertzNumber(5123000)}%S" == "5.123MHz")
.....
``` 

Also fails the test spinal.core.PhysicalNumbers

### PR DESCRIPTION
**Pull request by Readon**
Closes #1559 

# Context, Motivation & Description

avoid use official f-interpolator, use fp"xxxxx". 
This will change API.

# Impact on code generation

# Checklist

- [ ] Unit tests were added
- [x] API changes are or will be documented:
  - using Scaladoc comments: `/** */`?
  - on [RTD](https://github.com/SpinalHDL/SpinalDoc-RTD)?
  - thanks to a [new tracking issue on RTD](https://github.com/SpinalHDL/SpinalDoc-RTD/issues/new?title=Document%20XXX&body=Do%20not%20merge%20until%20SpinalHDL/SpinalHDL%23XXX%20has%20not%20been%20merged)?

### CODE REVIEW

**Comment by Dolu1990** [comment]
Thanks ^^ 
One thing is why fp ?
As that interpolator is type agnostic, could be sf instead ? (Spinal Formater)

**Comment by Readon** [comment]
> Thanks ^^ One thing is why fp ? As that interpolator is type agnostic, could be sf instead ? (Spinal Formater)

it's formatter for physical number^^
spinal formatter seems can cover this.

**Comment by Dolu1990** [comment]
i would say, let's go for sp instead of fp, as in the future other issues like that could be workaround the same way.

**Comment by Readon** [comment]
> i would say, let's go for sp instead of fp, as in the future other issues like that could be workaround the same way.

sf is better IMO, this code could be worked not only for physical number but also other class extended java.util.Formattable

**Pull request merged**
