### PR TITLE
fix mill support cross platform.

### PR DESCRIPTION
**Pull request by Readon**
Closes #1506
Closes #1516

# Context, Motivation & Description

# Impact on code generation

# Checklist

- [ ] Unit tests were added
- [ ] API changes are or will be documented:
  - using Scaladoc comments: `/** */`?
  - on [RTD](https://github.com/SpinalHDL/SpinalDoc-RTD)?
  - thanks to a [new tracking issue on RTD](https://github.com/SpinalHDL/SpinalDoc-RTD/issues/new?title=Document%20XXX&body=Do%20not%20merge%20until%20SpinalHDL/SpinalHDL%23XXX%20has%20not%20been%20merged)?

### CODE REVIEW

**Comment by Readon** [comment]
"com.lihaoyi" %% "sourcecode" % "0.3.0" is already imported in SpinalHDL. 
Expecting no extra packages is required.

**Comment by Readon** [comment]
The original method is to link Version.sc to Version.scala, which should be void. 
The revert makes files need be removed and add back then.

I have it merged to the dev now.

**Comment by Readon** [comment]
However, myself does not use SpinalHDL as submodule, can you recommend some repos for test?

**Comment by Dolu1990** [comment]
It work great, thanks ^^

Tested with SpinalHDL + VexRiscv:dev cloned in the same parent folder

**Pull request merged**
