### PR TITLE
Regif

### PR DESCRIPTION
**Pull request by jijingg**
i creat description of new RegisterBank Solution of Regif at #237. the main work is completed, but it'is not the final version, there are still some details to be polished.

### CODE REVIEW

**Comment by Dolu1990** [comment]
Thats cool, i also agree that the bus slave factory miss this many of those primitives, also the feild aproche can be quite usefull, and the arguement to specify the access kind too :D
What's about integrating it in the BusSlaveFactory ?

**Comment by Dolu1990** [comment]
For what are you using macro exactly ? Did you tried having RegInst extending Nameable ? 
Because in SpinalHDL everything extending Nameable will get a name from the enclosing Component/Area.

**Comment by jijingg** [comment]
There are three places to use signals name  
**case1,case2** used for Document-generate , 
**case3** used for Meta signal generate.

I haven't used Nameable yet, i will try it soon.
all those process add to `addPrePopTask`, i'm not sure can Nameable worked in addPrePopTask, 
```scala
  component.addPrePopTask(() => {
    readGenerator()
    document(getModuleName)
  })
```
If nameable worked , it cans instead first two case.

## case1:
i need collect field Name "sftRest0" "sftRest1" for document generator 
this current  implement by implicit Macro 
```scala
val sftRest0 = REG.field(1 bits, RW, doc="soft reset")(implict Macro.symbolName)
val sftRest0 = REG.field(1 bits, RW, doc="soft reset")(implict Macro.symbolName)
```
## case2:
i need get the Component name for document title .
Although you can explicitly generate documents like`busif.document("Example")`, 
but I think it's better to do it automatically
this current implement by implict Macro too 
```scala 
object BusInterface {
  def apply(bus: Apb3, sizeMap: SizeMapping, selID: Int)(implicit moduleName: ClassName): BusIf = Apb3BusInterface(bus, sizeMap, selID)(moduleName)
```

## case3:
a interrupt Example, there three triggers `tx_done`,`rx_done`,`frame_end` 
```scala
class cpInterruptExample extends Component {
  val io = new Bundle {
    val tx_done, rx_done, frame_end = in Bool()
    val interrupt = out Bool()
    val apb = slave(Apb3(Apb3Config(16, 32)))
  }
  val busif = Apb3BusInterface(io.apb, (0x000, 100 Byte))
```
then i need manually add interrupt register interface like this
```scala 
  val M_CP_INT_EN    = busif.newReg(doc="cp int enable register")
  val tx_int_en      = M_CP_INT_EN.field(1 bits, RW, doc="tx interrupt enable register")
  val rx_int_en      = M_CP_INT_EN.field(1 bits, RW, doc="rx interrupt enable register")
  val frame_int_en   = M_CP_INT_EN.field(1 bits, RW, doc="frame interrupt enable register")
  val M_CP_INT_MASK  = busif.newReg(doc="cp int mask register")
  val tx_int_mask      = M_CP_INT_MASK.field(1 bits, RW, doc="tx interrupt mask register")
  val rx_int_mask      = M_CP_INT_MASK.field(1 bits, RW, doc="rx interrupt mask register")
  val frame_int_mask   = M_CP_INT_MASK.field(1 bits, RW, doc="frame interrupt mask register")
  val M_CP_INT_STATE   = busif.newReg(doc="cp int state register")
  val tx_int_state      = M_CP_INT_STATE.field(1 bits, RW, doc="tx interrupt state register")
  val rx_int_state      = M_CP_INT_STATE.field(1 bits, RW, doc="rx interrupt state register")
  val frame_int_state   = M_CP_INT_STATE.field(1 bits, RW, doc="frame interrupt state register")

  when(io.rx_done && rx_int_en(0)){tx_int_state(0).set()}
  when(io.tx_done && tx_int_en(0)){tx_int_state(0).set()}
  when(io.frame_end && frame_int_en(0)){tx_int_state(0).set()}

  io.interrupt := (tx_int_mask(0) && tx_int_state(0)  ||
    rx_int_mask(0) && rx_int_state(0) ||
    frame_int_mask(0) && frame_int_state(0))
```
so this is a very tedious and repetitive work,
a better way is creat a  Factory fucntion by Macros  auto complet those work instead manully creat them.

```scala 
io.interrupt := busif.interruptFactory2("M_CP", io.tx_done,io.rx_done,io.frame_end)
```
image

It's much more convenient than manually do that

**Comment by jijingg** [comment]
@Dolu1990  i'm going to integrate BusIf into BusSlaveFactory ,But there are some conflicts and repetitions between the old way and the new way。
It is necessary to change some parameters and functions as following, **is it acceptable?**
## SlaveFactory Args 
### Apb3
```scala
class Apb3SlaveFactory(bus: Apb3, selId: Int, dontCareReadData : Boolean = false)extends BusSlaveFactoryDelayed
```
chang to :
```scala
class Apb3SlaveFactory(bus: Apb3, sizeMap: SizeMapping, selId: Int = 0, readSync: Boolean = true)(implicit moduleName: ClassName) extends BusSlaveFactoryDelayed with BusIf
```
remove `dontCareReadData` instead `readSync`, add `sizeMap`
### AhbLite3
```scala
class AhbLite3SlaveFactory(bus: AhbLite3, incAddress: Int = 0) extends BusSlaveFactoryDelayed
```
change to 
```scala
class AhbLite3SlaveFactory(bus: AhbLite3,sizeMap: SizeMapping, selId: Int = 0, readSync: Boolean = true)(implicit moduleName: ClassName) extends BusSlaveFactoryDelayed with BusIf
```
### AxiLite4
```scala
class AxiLite4SlaveFactory(bus : AxiLite4) extends BusSlaveFactoryDelayed
```
change to
```scala 
class AxiLite4SlaveFactory(bus : AxiLite4,sizeMap: SizeMapping, selId: Int = 0, readSync: Boolean = true)(implicit moduleName: ClassName) extends BusSlaveFactoryDelayed with BusIf
```
## Register Operation
old way:
```scala 
 busif.creatReadOnly()           //RO
 busif.createReadAndWrite()      //RW
 busif.createWriteOnly()         //WO
 busif.creatReadAndClearOnSet    //W1C
...
```
new way
```scala
val REG0 = busif.newReg()
REG0.field(2 bits, "RO")
REG0.field(5 bits, "RW")
REG0.field(2 bits, "WO")
REG0.field(1 bits, "W1C")
...
..
```
the new way can instead the old way. Of course, we can keep the old register operation function.
 But the SlaveFactory args need change . is it OK?

**Comment by Dolu1990** [comment]
hmmm, that wasn't exactly what i was thinking about, maybe the best would be to do a voice call somehow ? it would be more interractive than trying to describe our idea by text in here.

Would that be fine for you ?

**Comment by jijingg** [comment]
@Dolu1990 I’ m bad on oral english XD,  i will try , How about tomorrow, December 21, 2019?  What time is convenient for you? By the way, tell me your time zone.  I'm in Shanghai

**Comment by Dolu1990** [comment]
Ahhh let’s try XD
I’m in Switzerland gtm +1
Hmmm tomorrow i woulnd not be available before too late for you, but what’s about saturday morning for you, friday evening for me ?

**Comment by jijingg** [comment]
Thats ok , Sat day 7:00 for me, GTM+1 0:00 for you ,here is my skype https://join.skype.com/invite/pltad4Khm00V

**Comment by Dolu1990** [comment]
@jijingg Ok for me :)

**Comment by jijingg** [comment]
@Dolu1990 Thanks for you time.  Forgive my bad english  :joy: 
Let me summarize for our talk:

1. keep `dontareReadData` arg, keep the BusSlaveFactory structure.
2. add `sizeMap` to SlaveFactory as an option for overflow check .
3. get Component Name by `classOf(component.current)` instead implicit Macro way 
4. keep the old way `creatReadOnly,creatReadWrite.. etc.`  and new way `reg.field(xxx)...` together
5. will merge into next version SpinalHDL1.3.8

But there still have some problems, the old way `creatReaWrite` only collect filed-name after the Component object created like this `(new MyRegBank).busif.generateDoucment`.  but the new way 
`Reg0.field(2 bits, RW, "description")` will generat document before `new MyRegBank` object creat.
so i think the better way is generate document automatic ,do not need manually `(new MyRegBank).busif.generateDoucment`

**Comment by piegamesde** [comment]
What is the state of this? SpinalHDL 1.3.8 is out and this still isn't merged :(

**Pull request merged**
