### PR TITLE
add order parameter for StreamWidthAdapter with corresponding test.

### PR DESCRIPTION
**Pull request by Readon**
fix the problem that when padding = true the width miss match reported.
the reason is that resized function could not get correct bits width from assignFromBits function.

### CODE REVIEW

**Comment by Readon** [comment]
- [x] Did you add some test code?
 - [x] Did you add appropriate documentation in docs/src?
Wait the merge of this patch.
 - [x] Did you state the API impact?
 - [ ] Did you specify the code generation impact?
     consistent with old style.
 - [ ] Did you request a desired merge strategy?
     no 
 - [ ] Did you add text to be included in the Release
     What does this means?

**Comment by Dolu1990** [comment]
hmm weird, do you have an example of configuration where it was failing ?

**Comment by Readon** [comment]
&nbsp;you can test it with the test case with padding in scalatest dir.



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 25, 2022 18:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SpinalHDL/SpinalHDL] add order parameter for StreamWidthAdapterwith corresponding test. (PR #656)




 
hmm weird, do you have an example of configuration where it was failing ?

**Comment by Dolu1990** [comment]
Thanks ^^

**Pull request merged**
