### PR TITLE
Prove for fifo.

### PR DESCRIPTION
**Pull request by Readon**
It's weird that when I move some formal code to fifo, then "HIERARCHY VIOLATION ..." and "OLD NETLIST RE-USED : Memory port Mem.readAsync(x) ..." errors take place.

The only thing I have done is move formalContains checking into StreamFifo, which act a little different while prove then ram.

### CODE REVIEW

**Comment by Dolu1990** [comment]
Did you had that change when you tested : 
https://github.com/SpinalHDL/SpinalHDL/commit/f23ae83fe7703512d90e82ac6b95dbecd49f8e62#diff-1c1a0c012fde8f34b5db6150c4418753c46fa0f07e4fa5ffd37835cfebaf9314R239 

? 
Because it allows usage of Mem.apply(Int) inside the netlist if the formal generation flag is enabled.

**Comment by Readon** [comment]
yes，I have merged all latest patchs



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 30, 2022 01:01 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SpinalHDL/SpinalHDL] Prove for fifo. (PR #706)




 
Did you had that change when you tested :
 f23ae83#diff-1c1a0c012fde8f34b5db6150c4418753c46fa0f07e4fa5ffd37835cfebaf9314R239
 
?
 Because it allows usage of Mem.apply(Int) inside the netlist if the formal generation flag is enabled.

**Comment by Readon** [comment]
It worked now.

**Comment by Dolu1990** [comment]
thanks  ^^

**Pull request merged**
