### PR TITLE
Add DDR2 support for NexysA7

### PR DESCRIPTION
**Pull request by roman3017**
Please note that RESETn should be false for DDR2, since there is no reset pin. But I could not compile it. So I am leaving it true for now and connecting DDR reset pin to SW[0] on NexysA7 board.

### CODE REVIEW

**Comment by Dolu1990** [comment]
Thanks, i just got something equivalent during a train trip, also, now the DDR2 work in simulation + BL4 is ok :)

**Comment by Dolu1990** [comment]
(https://github.com/SpinalHDL/SpinalHDL/commit/87a7ce0c11a37c32c0db9ae7ed7e3901fc639977)

**Comment by roman3017** [comment]
@Dolu1990 The change https://github.com/SpinalHDL/SpinalHDL/commit/87a7ce0c11a37c32c0db9ae7ed7e3901fc639977 has broken target `saxon.board.digilent.NexysA7Linux`. Seems like RESETn pin is still defined. This is a temporary workaround:
```diff
diff --git a/lib/src/main/scala/spinal/lib/memory/sdram/xdr/Xdr.scala b/lib/src/main/scala/spinal/lib/memory/sdram/xdr/Xdr.scala
index 9417fd3d..12e2d217 100644
--- a/lib/src/main/scala/spinal/lib/memory/sdram/xdr/Xdr.scala
+++ b/lib/src/main/scala/spinal/lib/memory/sdram/xdr/Xdr.scala
@@ -143,7 +143,7 @@ case class SdramXdrIo(g : SdramLayout) extends Bundle with IMasterSlave {
 
   val CK, CKn = out Bool()
   val ODT = out Bool()
-  val RESETn = out Bool()
+  val RESETn = True
 
   val DM   = Bits(g.bytePerWord bits)
   val DQ    = Analog(Bits(g.dataWidth bits))
diff --git a/lib/src/main/scala/spinal/lib/memory/sdram/xdr/phy/XilinxS7Phy.scala b/lib/src/main/scala/spinal/lib/memory/sdram/xdr/phy/XilinxS7Phy.scala
index 2803e9d3..f23d6132 100644
--- a/lib/src/main/scala/spinal/lib/memory/sdram/xdr/phy/XilinxS7Phy.scala
+++ b/lib/src/main/scala/spinal/lib/memory/sdram/xdr/phy/XilinxS7Phy.scala
@@ -112,7 +112,7 @@ case class XilinxS7Phy(sl : SdramLayout,
   io.sdram.CSn  := sdrToOutput("CSn", io.ctrl.phases.map(p => RegNext(p.CSn )))
   io.sdram.RASn := sdrToOutput("RASn", io.ctrl.phases.map(p => RegNext(p.RASn)))
   io.sdram.WEn  := sdrToOutput("WEn", io.ctrl.phases.map(p => RegNext(p.WEn )))
-  io.sdram.RESETn := sdrToOutput("RESETn", io.ctrl.phases.map(p => RegNext(p.RESETn)))
+//  io.sdram.RESETn := sdrToOutput("RESETn", io.ctrl.phases.map(p => RegNext(p.RESETn)))
   io.sdram.ODT    := sdrToOutput("ODT", io.ctrl.phases.map(p => RegNext(p.ODT)))
```

**Comment by Dolu1990** [comment]
@roman3017 Right, i just submited a fix.

I updated the bootloader / sdramInit software to work with the recent changes, also the DDR2 is configured in CAS 5 now.
So, i did some simulations. including simulations of the whole SoC against a DDR2 simulation model from micron, and that seem ok. There is some hope for it to work.

So let's me know how it goes for you on hardware :)

Do not forget to pull and update submodules,  SaxonSoc branch => ulx3s_newdram

**Comment by roman3017** [comment]
It works, thank you very much. Also BL4 and CL5 work on ulx3s_newdram branch.

**Pull request closed without merging**
