### PR TITLE
Foldable unit test

### PR DESCRIPTION
**Pull request by wifasoi**
Is still not perfect, bet you can check the result here:
https://travis-ci.com/wifasoi/SpinalHDL/jobs/195742247

There are still some u-test that do not behave, so I'll mark this PR as a WIP.

Explanation: (the magic souce is [here](https://github.com/SpinalHDL/SpinalHDL/compare/dev...wifasoi:foldable-utest?expand=1#diff-e2080510c7aa6a0d1ccc828264aab096))
- This PR will print the travis "magic string" to permit each unit test to have a foldable log.
- Each fold will have a name corresponding to the unit-test class name.
- This behavior will trigger only when the TRAVIS env variable is defined (the value doesn't matter)

### CODE REVIEW

**Comment by Dolu1990** [comment]
Ok :D
Let's me know when that's ok

**Comment by wifasoi** [comment]
@typingArtist it makes sense.. I'll try that.
This PR is a bit stale because I'm a bit busy (but i can cut some time this evening for implementing your suggestion)

**Comment by wifasoi** [comment]
Ok, this solution is not perfect.. but this will make travis show all the logs.

**Comment by numero-744** [comment]
Hmm it seems Travis integration stopped a year ago (in favor of GitHub actions?). Maybe this PR can be closed?

**Comment by numero-744** [comment]
Hmm it seems Travis integration stopped a year ago (in favor of GitHub actions?). Maybe this PR can be closed?

**Comment by wifasoi** [comment]
Agree

**Pull request closed without merging**
