### PR TITLE
AxiMemorySim Random object as parameter

### PR DESCRIPTION
**Pull request by knapheide**
# Context, Motivation & Description

Optionally pass a `scala.util.Random` object into `AxiMemorySim`, so tests can be reproducible.

# Impact on code generation

# Checklist

- [ ] Unit tests were added
- [ ] API changes are or will be documented:
  - using Scaladoc comments: `/** */`?
  - on [RTD](https://github.com/SpinalHDL/SpinalDoc-RTD)?
  - thanks to a [new tracking issue on RTD](https://github.com/SpinalHDL/SpinalDoc-RTD/issues/new?title=Document%20XXX&body=Do%20not%20merge%20until%20SpinalHDL/SpinalHDL%23XXX%20has%20not%20been%20merged)?

### CODE REVIEW

**Comment by Readon** [comment]
Maybe a gen function is preferred but a random object?

**Comment by andreasWallner** [comment]
I'm not sure I understand the use-case you'd use this for. To make a test reproducible have a few methods to provide a seed that will ensure that other simulation agents (e.g. the Stream ones) will also have reproducible behavior (e.g.  via the `seed` parameter to `doSim` or via an environment variable `SPINAL_SIM_SEED`).
Do you have a use-case in mind where you just want the AxiMemorySim the behave reproducible but nothing else?

**Comment by knapheide** [comment]
Ah, i didnt realize that `doSim` sets the seed globally.

That wont work though when running multiple simulations in parallel in the same process, right?
I probably should just stop doing that

**Comment by andreasWallner** [comment]
What would be your desired outcome when running multiple simulations in parallel? All our examples enable forking, so a separate jvm process is started for each test - so you can run tests in parallel and still have reproducible tests.

**Comment by knapheide** [comment]
I am iterating over a bunch of configurations i want to test and it just seemed easiest to speed this up using `concurrent.Future.traverse`.
But its not a big problem, i can either look into scalatest, or spawn separate processes myself. I just didnt know that parallel simulations in the same process arent supported.

**Pull request closed without merging**
