### PR TITLE
a little improve on interface

### PR DESCRIPTION
**Pull request by yportne13**
add a basic support for bundle in interface.
add a basic sim for interface
If there's no hurry to release a new version, this PR can be kept open for now and will include a little more improvements and test cases.

### CODE REVIEW

**Comment by Dolu1990** [comment]
Let's me know when you want a review ^^

**Comment by yportne13** [comment]
one last thing, for Bundle, I can call `parent` on the element to get that Bundle. But for Vec, what should I do?

**Comment by Dolu1990** [comment]
The push just above will now set parent of vec aswell

**Comment by yportne13** [comment]
done @Dolu1990

**Pull request merged**
