### PR TITLE
Add `synopsys_sim.setup` and other environment setup support

### PR DESCRIPTION
**Pull request by wswslzp**
1. Now user can provide a `synopsys_sim.setup` file to VCS;
2. Customized scripts or functions can be executed before the VCS analysis step now.

### CODE REVIEW

**Review by jjyy-Huang — COMMENTED** [review]
Thanks for this. It will be more convenient! : )

**Comment by wswslzp** [comment]
Hi @Dolu1990, I think this PR can be merged now.

**Comment by jijingg** [comment]
@wswslzp thanks 
should you add usage or example to document.

**Comment by wswslzp** [comment]
Soon I will add.

**Pull request merged**
