### PR TITLE
Allow braces

### PR DESCRIPTION
**Pull request by numero-744**
Blocking point: missing documentation for 2 methods.

### CODE REVIEW

**Comment by kleinai** [comment]
So you've added braces to a few functions but then reformatted all of Data and renamed a functions? Maybe we should move the formatting and renaming changes to another PR? I think a few people have tried to reformat the code before.

**Comment by numero-744** [comment]
Well actually, I have the "auto-format" reflex (just like the "save" reflex XD), which is not an issue if the code is kept formatted using the official style / program.

I'm gonna split this PR in 3:

* allow braces
* rename 2 private functions
* add a GH action to check that code is correctly formatted

So that we can discuss each of them.

**Comment by Readon** [comment]
there are disscussions on format tools in #535 and #539 .

**Comment by numero-744** [comment]
I cannot find documentation for those 2 items:

* `allowPartialyAssigned`: should it be linked to a new RTD page about `PARTIALLY ASSIGNED REGISTER` design error? [Phase.scala:2025](https://github.com/SpinalHDL/SpinalHDL/blob/d12c8b917eb2a3680f5eb15dac4d1a34b1bbcdcd/core/src/main/scala/spinal/core/internals/Phase.scala#L2025))
* `noBackendCombMerge`: merge what?

**Comment by Dolu1990** [comment]
@numero-744 

> allowPartialyAssigned

Ahh yes it isn't documented, yes it is to skyp the PARTIALLY ASSIGNED REGISTER check for the given signal.
would need some doc ^^

> noBackendCombMerge

With that option enable, each combinatorial signal which require a always/process block (HDL) will have its own one. While if the option is disabled, then SpinalHDL will merge always/process block which use the same when statements ( but because HDL sucks, it may create endless simulation loop in some specific cross dependence cases ).

**Comment by Dolu1990** [comment]
If tests pass it can be merged ^^

**Pull request merged**
