### PR TITLE
Add SystemRDL RegIf exporter

### PR DESCRIPTION
**Pull request by MarekPikula**
SystemRDL can be used for project documentation or code generation. Generating SystemRDL from RegIf is especially useful in projects incorporating SpinalHDL IP cores when other IPs have the register interface documentation available in SystemRDL.

Relates to SpinalHDL/SpinalDoc-RTD#125.

Example export snippet:

```scala
val regs = BusInterface(...)

val pwm_enable = regs
  .newRegAt(RegMap.PWM_ENABLE, "Enable PWM channels.")
  .field(Bool, RW, 0)

val pwm_a_duty = regs
  .newRegAt(RegMap.PWM_A_DUTY, "PWM channel A duty cycle.")
  .field(UInt(config.pwm.dutyCycleWidth), RW, 0x10)

val pwm_b_duty = regs
  .newRegAt(RegMap.PWM_B_DUTY, "PWM channel B duty cycle.")
  .field(UInt(config.pwm.dutyCycleWidth), RW, 0x20)

val sw_rst = regs
  .newRegAt(
    RegMap.SW_RST,
    "Software reset."
  )
  .field(Bool, W1P, 0)

regs.accept(SystemRdlGenerator("regs", "my_ip", Some("My IP"), Some("Example IP register map.")))
```

```systemrdl
// SystemRDL 2.0 register description for crosslink
// Generated from SpinalHDL RegIf definition. Don't edit.
// Date: Thu Oct 13 17:10:03 CEST 2022

addrmap my_ip {
    name = "My IP";
    desc = "Example IP register map.";

    default hw = rw;
    default sw = rw;

    reg {
        name = "pwm_enable";
        desc = "Enable PWM channels.";

        field {
            name = "pwm_enable";
            desc = "";
            reset = 0x0;
            sw = rw;
        } pwm_enable[0:0];
    } pwm_enable @ 0x54;

    reg {
        name = "pwm_a_duty";
        desc = "PWM channel A duty cycle.";

        field {
            name = "pwm_a_duty";
            desc = "";
            reset = 0x10;
            sw = rw;
        } pwm_a_duty[7:0];
    } pwm_a_duty @ 0x55;

    reg {
        name = "pwm_b_duty";
        desc = "PWM channel B duty cycle.";

        field {
            name = "pwm_b_duty";
            desc = "";
            reset = 0x20;
            sw = rw;
        } pwm_b_duty[7:0];
    } pwm_b_duty @ 0x57;

    reg {
        name = "sw_rst";
        desc = "Software reset.";

        field {
            name = "sw_rst";
            desc = "";
            reset = 0x0;
            sw = rw;
            singlepulse;  // On 1 pulse on matching bit.
        } sw_rst[0:0];
    } sw_rst @ 0xF9;
};
```

### CODE REVIEW

**Comment by Dolu1990** [comment]
@jijingg (notification :))

**Comment by MarekPikula** [comment]
I can see doc needed label. What precisely should be added and where?

**Comment by numero-744** [comment]
I think here: [RegIf &mdash; SpinalHDL  documentation](https://spinalhdl.github.io/SpinalDoc-RTD/master/SpinalHDL/Libraries/regIf.html#automatic-documentation-generation) (source to edit: [Libraries/regIf.rst](https://github.com/SpinalHDL/SpinalDoc-RTD/blob/master/source/SpinalHDL/Libraries/regIf.rst), could not point to the specific line because GitHub)

**Comment by numero-744** [comment]
Thanks for the doc PR

**Comment by MarekPikula** [comment]
What needs to happen to have it merged (i.e., who needs to approve)?

**Comment by numero-744** [comment]
LGTM but I'm not a professional of SpinalHDL :wink:

I assigned @jijingg, who seems to know this part of the lib really well.

Else, maybe @Dolu1990 can also review?

**Comment by Dolu1990** [comment]
@numero-744 Ahh i don't know enough about the RefIf things ^^
I'm not realy a good reviewer for it.

**Comment by kleinai** [comment]
I'll bring it in as I'll be working around in RegIf.

Thanks!

**Pull request merged**
