### PR TITLE
docs: add help for contributors

### PR DESCRIPTION
**Pull request by numero-744**
Closes #619 and #902

### CODE REVIEW

**Comment by numero-744** [comment]
I'll need help for some descriptions in [CONTRIBUTING.md:29-33](https://github.com/SpinalHDL/SpinalHDL/pull/909/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R29-R33).

**Comment by numero-744** [comment]
@Dolu1990 It might be interesting for you :wink: (as far as we keep labels updated): https://github.com/SpinalHDL/SpinalHDL/pull/909/commits/81eac8ffce03ee0c040079950e7033a1500083da?short_path=eca12c0#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055

**Comment by Dolu1990** [comment]
> @Dolu1990 It might be interesting for you wink (as far as we keep labels updated): [81eac8f?short_path=eca12c0#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055](https://github.com/SpinalHDL/SpinalHDL/commit/81eac8ffce03ee0c040079950e7033a1500083da?short_path=eca12c0#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055)

Rawrrrr <3

**Comment by numero-744** [comment]
@Dolu1990 I need help to define these things (you can copy-paste this `md` block and fill in the blanks to save time :smile:):

```markdown
* debugger:
* demo:
* Dockerfile:
* idslpayload:
* idslplugin:
* sim/simulation_pluginssim/simulation_plugins:
* sim/yolo:
* tester/src/__init__.py:
* core/src/test/scala/landa:
* tester/src/main:
* tester/src/test/scala/spinal/tester/generator:
* tester/src/test/scala/spinal/tester/misc:
* tester/src/test/scala/spinal/tester/pending:
* tester/src/test/scala/spinal/tester/scalatest:
```

Personal note: App can be used in tests for compile-only checks, to save time running things.

**Comment by Dolu1990** [comment]
@numero-744 I did some cleaning in the repo and filled comments after the todo.
I tried to push on your branch, but didn't had accesses.
I pushed what i wanted to propose in https://github.com/SpinalHDL/SpinalHDL/tree/contributor-guide
Feel free to merge it on your repo :D

**Comment by numero-744** [comment]
Thanks, I took the two first commits, rebased on dev and I'll edit CONTRIBUTING by-hand.

**Comment by numero-744** [comment]
@Dolu1990 

* Should we rename `yolo` as `rtl`, `hardware` or any more descriptive name?
* Should we flatten it?
* For the scratchpads I am not sure we should keep them as-is in the long term, but I'll let them as-is for now.

**Comment by Dolu1990** [comment]
> Should we rename yolo as rtl, hardware or any more descriptive name?

Why not, but you would also need to rename the few tests which refer to it too (in some strings)
grep -r "yolo/" .  => 5 hit

> Should we flatten it?

Yes why not.

> For the scratchpads I am not sure we should keep them as-is in the long term, but I'll let them as-is for now.

Sure it is all messy.
Also note, some of the scratchpad are used as code samples for some presentation / documentation

**Comment by numero-744** [comment]
To perform renaming I usually check that the current situation works, then I start search & replacing, and I check that I didn't break anything.

Here the first step fails: currently on `dev` I cannot run `App`s of `sim/src/test` because of missing `simulation_plugins/SharedMemIface.cpp` among other errors which depend on the background tool (here it is for GHDL).

@Dolu1990 What should I do?

**Comment by Dolu1990** [comment]
> Here the first step fails: currently on dev I cannot run Apps of sim/src/test because of missing simulation_plugins/SharedMemIface.cpp among other errors which depend on the background tool (here it is for GHDL).

Ahhh, don't botter, this code is only used in exceptional situation. i don't think we realy need to maintaine it. It is mostly there as a backup.

**Comment by numero-744** [comment]
Backup in case of what? Can `git` history be the backup? :hand_over_mouth:

**Comment by Dolu1990** [comment]
> Backup in case of what?

In case of heavy debugging of the low level API or a new simulation backend

> Can git history be the backup?

Things which leave upstream and goes in the history would be lost from our view, and so forgotten ^^

**Comment by numero-744** [comment]
Hmpf, having to remember what code should be maintained vs what code should not is too much for me (I guess for anyone who is not the initial author of this code), so I'll not change the folder name.

**Comment by numero-744** [comment]
* [x] rebased on dev
* [x] completed list of folders
* [x] checked that the PR template is used by GitHub

The folder structure description can be a good starting point to discuss future rework of this structure (for instance for tests which are currently all in one folder :sweat_smile:)

**Comment by numero-744** [comment]
@Dolu1990 ready for review and merge if okay for you

**Comment by Dolu1990** [comment]
Nice, thanks :D

**Pull request merged**
