### PR TITLE
Move doCmd to misc and cleanup duplicate code in spinalhdl.eda.bench

### PR DESCRIPTION
**Pull request by jiegec**
Move duplicated `doCmd` function to Misc.scala and cleanup some unused code.

### CODE REVIEW

**Comment by volatile-static** [comment]
Hello, @jiegec 
I pulled a request just now. #374 
By coincidence, your #373 has some conflicts with mine. And I have no idea what to do.

**Comment by jiegec** [comment]
> Hello, @jiegec
> I pulled a request just now. #374
> By coincidence, your #373 has some conflicts with mine. And I have no idea what to do.

Okay, let me rebase my commit.

**Comment by volatile-static** [comment]
I see.. I had batter close my pr #374 first😂

**Comment by jiegec** [comment]
> I see.. I had batter close my pr #374 first😂

Oh, that's not needed, you can just leave it open.

**Comment by Dolu1990** [comment]
Thanks ^^

**Pull request merged**
