### PR TITLE
avoid to use unnamed workspace name while do formal verification.

### PR DESCRIPTION
**Pull request by Readon**
Closes #

# Context, Motivation & Description

# Impact on code generation

# Checklist

- [ ] Unit tests were added
- [ ] API changes are or will be documented:
  - using Scaladoc comments: `/** */`?
  - on [RTD](https://github.com/SpinalHDL/SpinalDoc-RTD)?
  - thanks to a [new tracking issue on RTD](https://github.com/SpinalHDL/SpinalDoc-RTD/issues/new?title=Document%20XXX&body=Do%20not%20merge%20until%20SpinalHDL/SpinalHDL%23XXX%20has%20not%20been%20merged)?

### CODE REVIEW

**Comment by Readon** [comment]
Use the wrapping SpinalFormalFunSuite class name as the workspace name.
This can put the verification files into categories by name.

**Comment by Dolu1990** [comment]
Feel free to merge ^^

**Comment by Dolu1990** [comment]
SpinalSimDmaSgTester should be fixed with https://github.com/SpinalHDL/SpinalHDL/commit/eb3e5776bc668bb15ad4696dd970357050cfb4ee
Or the issue persists ?

**Comment by Readon** [comment]
> SpinalSimDmaSgTester should be fixed with [eb3e577](https://github.com/SpinalHDL/SpinalHDL/commit/eb3e5776bc668bb15ad4696dd970357050cfb4ee) Or the issue persists ?

I will try to merge them first. It was not included though.

**Pull request merged**
