### PR TITLE
Composable exp

### PR DESCRIPTION
**Pull request by Dolu1990**
Sync VexiiRiscv related improvments

### CODE REVIEW

**Comment by Readon** [comment]
It seems there are a lot of changes there.

**Comment by Dolu1990** [comment]
Yes, quite a fire little fix there and there of a few line each.
The biggest changes are : 
- Verilator waves being saved into a folder which is named with the test name itself.
- making the vivado flow generating a proper vivado project instead of TCL only stuff.

If you are unconfortable with any of those change, i can isolate it into its dedicated PR.

**Comment by Readon** [comment]
> Yes, quite a fire little fix there and there of a few line each. The biggest changes are :
> 
> * Verilator waves being saved into a folder which is named with the test name itself.
> * making the vivado flow generating a proper vivado project instead of TCL only stuff.
> 
> If you are unconfortable with any of those change, i can isolate it into its dedicated PR.

It's OK. It would be perfect if the doc can get updated.

**Comment by Dolu1990** [comment]
Added the dac in https://github.com/SpinalHDL/SpinalDoc-RTD/commit/01659ba9afa3989a7c780ef55edbc24927d28299

**Pull request merged**
