### PR TITLE
Binary system utils

### PR DESCRIPTION
**Pull request by jijingg**
@Dolu1990  I'm sorry for there have so much PR has delay so long time  for the reason of my busy work .  I will try my best to close that one by one .

The first one is binarySystem .

These things have nothing to do with HDL, but they are very common in digital systems,  In particular, the algorithm reference model is widely used. In addition, it is also very useful in building testbench. so I put them in `spinal.lib` rather than `spinal.core`

I'll add it to the SpinalHDL document later too.

Do you have any other suggestions？

``` scala 
import spinal.core.lib._ 

println(o"1234567" )                                             =>  342391                                     
println(x"89bef" )                                               =>  564207                                     
println(b"1101" )                                                =>  13                                         
println("11001".asHex)                                           =>  69633                                      
println("11001".asDec)                                           =>  11001                                      
println("11001".asOct)                                           =>  4609                                       
println("11001".asBin)                                           =>  25                                         
println("38f".hexToBinInts)                                      =>  List(1, 1, 1, 1, 0, 0, 0, 1, 1, 1)         
println("38f".hexToBinIntsAlign)                                 =>  List(1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0)   
println(129.hexString)                                           =>  81                                         
println(129.hexString(16))                                       =>  0081                                       
println(129.octString)                                           =>  201                                        
println(129.octString(16))                                       =>  000201                                     
println(129.binString)                                           =>  10000001                                   
println(129.binString(16))                                       =>  0000000010000001                           
println(129.toBinInts)                                           =>  List(1, 0, 0, 0, 0, 0, 0, 1)               
println(129.toBinInts(5))                                        =>  List(1, 0, 0, 0, 0, 0, 0, 1)               
println(129.toDecInts)                                           =>  List(9, 2, 1)                              
println(129.toDecInts(5))                                        =>  List(9, 2, 1, 0, 0)                        
println(129.toOctInts)                                           =>  List(1, 0, 2)                              
println(129.toOctInts(5))                                        =>  List(1, 0, 2)                              
println(List(1,0,1,1,0,1,0,1,0,1,1,1,1).binIntsToBigInt)         =>  7853                                       
println(List(1,0,1,1,0,1,0,1,0,1,1,1,1).binIntsToInt)            =>  7853                                       
println(List(1,0,1,1,0,1,0,1,0,1,1,1,1).binIntsToLong)           =>  7853                                       
println(List(1,0,1,1,0,1,0,1,0,1,1,1,1).binIntsToHex)            =>  1ead                                       
println(List(1,0,1,1,0,1,0,1,0,1,1,1,1).binIntsToOct)            =>  17255                                      
println(List(1,0,1,1,0,1,0,1,0,1,1,1,1).binIntsToHexAlignHigh)   =>  f568                                       
println(List(1,0,1,1,0,1,0,1,0,1,1,1,1).binIntsToOctAlignHigh)   =>  75264                                      
println(List(1,0,0,0,1,1,0,1,1).binIntsToHex)                    =>  1b1                                        
println(List(1,0,0,0,1,1,0,1,1).binIntsToHexAlignHigh)           =>  d88                                        
println(List(1,0,0,0,1,1,0,1,1,0).binIntsToOct)                  =>  0661                                       
println(List(1,0,0,0,1,1,0,1,1,0).binIntsToOctAlignHigh)         =>  3304                                       
println(List(1, 0, 1, 0, 1, 1, 1, 0, 1).binIntsToInt)            =>  373                                        
println(349.toBinInts)                                           =>  List(1, 0, 1, 1, 1, 0, 1, 0, 1)    
println(x"32456".toBinInts())                                    =>  List(0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1)  
println(o"32456".toBinInts())                                    =>  List(0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1)              
println(o"32456".toBinInts(15))                                  =>  List(0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0)                                        
```

```scala
assert("32456" == o"32456".toBinInts().binIntsToOct)
assert("32456" == x"32456".toBinInts().binIntsToHex)
assert(324565 == 324565.toBinInts().binIntsToInt)
assert(32 == 32.toBinInts().binIntsToInt)
assert(134 == 134.toBinInts().binIntsToInt)
assert(BigInt("abcdef0123456789abcdef", 16) == BigInt("abcdef0123456789abcdef", 16).toBinInts().binIntsToBigInt)
```

### CODE REVIEW

**Comment by Dolu1990** [comment]
Hi ^^

About toBinst al all other ???st

What the st stand for ?

**Comment by jijingg** [comment]
> Hi ^^
> 
> About toBinst al all other ???st
> 
> What the st stand for ?

Honestly, xxxst is not a standard, but string or hex to bits stream is very common request.  In encryption, CRC and Communication algorithm ,  we often need transform HexString to bits stream  or bits-stream to HexString .
```
BigInt("123456789abcdef987654321").toBinst
```
For general purposes,   in addition toBinst, I have also added toOctst and toDecst in case of need.
There may be some independent libraries to do this, but I don't want to import a dependent library for this. So I hope spinal Lib can add some such useful utils. 
When we look for those method next time, we don't need to rewrite it yourself.  Spinal just provides such a utils.

**Comment by Readon** [comment]
I guess it stand for a list.^^

**Comment by Dolu1990** [comment]
For toBinst, what's about renaming it to  "toBinInts" ? List[Int] => Ints.

Allowing future addition, as eventualy toBinBooleans(but not now)

**Comment by jijingg** [comment]
> For toBinst, what's about renaming it to "toBinInts" ? List[Int] => Ints.
> 
> Allowing future addition, as eventualy toBinBooleans(but not now)

it's make sense .  names are updated !

**Comment by Dolu1990** [comment]
Cool thanks :D

**Pull request merged**
